#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

zstyle ':prezto:module:editor:info:keymap:primary' format ' %B%F{1}❯%F{8}❯%f%b'

eval "$(rbenv init -)"
